package com.ftn.sbnz.model.models;

public enum VrstaKontraindikacije {
    MU,
    TRAUMA_GLAVE,
    OPERATIVNA_INTERVENCIJA,
    INTRAKRANIJALNA_HEMORAGIJA,
    GASTROINTESTINALNO_KRVARENJE,
    UROGENITALNO_KRVARENJE,
    ARTERIJSKA_PUNKCIJA,
    LUMBALNA_PUNKCIJA,
    AKUTNI_INFARKT_MIOKARDA
}
