package com.ftn.sbnz.model.models;

import lombok.Getter;

@Getter
public enum VrstaBolesti {
    OPERATIVNA_INTERVENCIJA,
    INTRAKRANIJALNA_HEMORAGIJA,
    GASTROINTESTINALNO_KRVARENJE,
    UROGENITALNO_KRVARENJE,
    ARTERIJSKA_PUNKCIJA,
    LUMBALNA_PUNKCIJA,
    AKUTNI_INFARKT_MIOKARDA
}
