spring:
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://localhost:5432/thrombolysis-decision
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
