package cep;

import com.ftn.sbnz.model.events.OtkucajSrcaEvent;
import com.ftn.sbnz.model.models.RadSrca;
import java.util.List;


declare AlarmZaRadSrca
    jmbgPacijenta: String
    radSrca: RadSrca
end

rule "Ukoliko je broj otkucaja srca veći od 100/min, to ukazuje na tahikardiju."
	when
		$otkucaj1: OtkucajSrcaEvent($jmbgPacijenta1: jmbgPacijenta, rrInterval == null)
        		Number(intValue > 10) from accumulate(
        		    $otkucaj2: OtkucajSrcaEvent(
        		        this != $otkucaj1,
        		        jmbgPacijenta == $jmbgPacijenta1,
                        this meets[1m] $otkucaj1
        		    ),
        		    count($otkucaj2)
        		)
		not(AlarmZaRadSrca(jmbgPacijenta == $jmbgPacijenta1, radSrca == RadSrca.UBRZAN))
	then
		System.out.println("ALARM ZA UBRZANI RAD SRCA");
		insert(new AlarmZaRadSrca($jmbgPacijenta1, RadSrca.UBRZAN));
end

rule "Ukoliko je broj otkucaja srca manji od 60/min, to ukazuje na bradikardiju."
	when
		$otkucaj1: OtkucajSrcaEvent($jmbgPacijenta1: jmbgPacijenta, rrInterval == null)
		Number(intValue == 5) from accumulate(
		    $otkucaj2: OtkucajSrcaEvent(
		        this != $otkucaj1,
		        jmbgPacijenta == $jmbgPacijenta1,
                this meets[1m] $otkucaj1
		    ),
		    count($otkucaj2)
		)
		not(AlarmZaRadSrca(jmbgPacijenta == $jmbgPacijenta1, reason == RadSrca.USPOREN))
	then
		System.out.println("ALARM ZA USPORENI RAD SRCA");
		insert(new AlarmZaRadSrca($jmbgPacijenta1, RadSrca.USPOREN));
end

rule "Ukoliko se poslednjih 5 RR intervala znatno razlikuju (razlika ≥ 4), sumnja se na atrijalnu fibrilaciju"
	when
		$otkucaj1: OtkucajSrcaEvent($jmbgPacijenta1: jmbgPacijenta, rrInterval != null)

		$posljednjih5: List(size >= 5) from collect(
                OtkucajSrcaEvent(jmbgPacijenta == $jmbgPacijenta1, rrInterval != null) over window:length(5)
            )
        accumulate(
                $i: OtkucajSrcaEvent() from $poslednjih5,
                $prev: OtkucajSrcaEvent(this != $i) from $poslednjih5,
                $difference: Integer(this != null) from ($i.getLength() - $prev.getLength());
                $differences: List() from collect($difference)
                $totalDifference: Integer() from sum($differences)
            )
		not(AlarmZaRadSrca(jmbgPacijenta == $jmbgPacijenta1, radSrca == RadSrca.USPOREN))
	then
		System.out.println("ALARM ZA ATRIJALNU FIBRILACIJU");
		insert(new AlarmZaRadSrca($jmbgPacijenta1, RadSrca.USPOREN));
end
