package cep;

import com.ftn.sbnz.model.models.AlarmEKG;
import com.ftn.sbnz.model.models.NIHHS;
import java.util.List;
import java.lang.Math;
import java.util.Date;
import java.lang.Integer;


rule "Iregularan NIHHS skor"
salience 30
	when
        $poslednjiNihhs: NIHHS($jmbgPacijenta1: jmbgPacijenta, $skor1: skor)
        $pretposlednjiElLista: List(size == 1) from accumulate(
            NIHHS(this != $poslednjiNihhs, jmbgPacijenta == $jmbgPacijenta1, $skor2: skor) over window:length(2),
            collectList($skor2)
        )
        $pretposlednjiNihhs: Integer() from $pretposlednjiElLista[0]
        eval(Math.abs($skor1 - $pretposlednjiNihhs) >= 4)
        not(AlarmEKG(jmbgPacijenta == $jmbgPacijenta1, iregularanNIIHS == true))

	then
	    System.out.println("Alarm - Kod pacijenta su uoceni iregularni NIHHS skorovi");
        insert(new AlarmEKG($jmbgPacijenta1, true));
end

