export enum NivoRizikaMu {
  NIZAK_RIZIK = 'NIZAK_RIZIK',
  VISOK_RIZIK = 'VISOK_RIZIK',
  PROCENA_U_TOKU = 'PROCENA_U_TOKU',
  PROCENA_RIZIKA_OD_ATRIJALNE_FIBRILACIJE = 'PROCENA_RIZIKA_OD_ATRIJALNE_FIBRILACIJE'
}
