export enum DecisionStatus {
  U_PROCESU,
  PRIHVACENA="PRIHVACENA",
  ODBIJENA="ODBIJENA",
  PRIHVACENA_FAZA_1="PRIHVACENA_FAZA_1",
  PRIHVACENA_FAZA_2="PRIHVACENA_FAZA_2",
  PRIHVACENA_FAZA_3="PRIHVACENA_FAZA_3",
  PRIHVACENA_FAZA_4="PRIHVACENA_FAZA_4",
  PRIHVACENA_FAZA_5="PRIHVACENA_FAZA_5",
  PRIHVACENA_FAZA_6="PRIHVACENA_FAZA_6",
}
