package forward;

import com.ftn.sbnz.model.events.OdlukaOTromboliziEvent;
import com.ftn.sbnz.model.models.StatusOdluke;

rule "Faza 3 - Ukoliko je sistolni pritisak preko 185 mmHg ili dijastolni preko 110 mmHg, pacijent nije podoban za terapiju."
no-loop true
salience 1000
	when
		$odlukaEvent: OdlukaOTromboliziEvent(statusOdluke == StatusOdluke.PRIHVACENA_FAZA_3, pritisak.getSistolni() > 185 || pritisak.getDijastolni() > 110)
	then
		System.out.println("Pacijent ne moze da primi terapiju jer ima visok pritisak.");
		modify ($odlukaEvent) { setStatusOdluke(StatusOdluke.ODBIJENA) };
end