package forward;

import com.ftn.sbnz.model.events.OdlukaOTromboliziEvent;
import com.ftn.sbnz.model.models.StatusOdluke;

rule "Faza 3 - Ukoliko pacijent ima nizak ili visok pritisak, nije podoban za primenu terapije."
no-loop true
salience 1000
	when
		$odlukaEvent: OdlukaOTromboliziEvent(statusOdluke == StatusOdluke.PRIHVACENA_FAZA_3,
		pritisak.getSistolni() > 185 || pritisak.getDijastolni() > 110)
	then
		modify ($odlukaEvent) { setStatusOdluke(StatusOdluke.ODBIJENA) };
end

