package forward;

import com.ftn.sbnz.model.models.NIHHS;
import com.ftn.sbnz.model.events.OdlukaOTromboliziEvent;
import com.ftn.sbnz.model.models.StatusOdluke;
import com.ftn.sbnz.model.models.ZnakIshemije;


rule "Faza 4 - Pacijent nije podoban za primenu terapije na osnovu NIHHS skora"
salience 20
	when
		$nihhs: NIHHS(skor < 4 || skor > 20)
	then
		System.out.println("Pacijent ciji je NIHHS skor " + $nihhs.getSkor() + " nije podoban za primenu terapije.");
		insert(new OdlukaOTromboliziEvent($nihhs.getIdOdluke(), StatusOdluke.ODBIJENA));
end

rule "Faza 4 - Pacijent jeste podoban za primenu terapije na osnovu NIHHS skora"
salience 20
	when
		$nihhs: NIHHS(skor >= 4 && skor <= 20)
	then
		System.out.println("Pacijent ciji je NIHHS skor " + $nihhs.getSkor() + " je podoban za primenu terapije.");
		insert(new OdlukaOTromboliziEvent($nihhs.getIdOdluke(), StatusOdluke.PRIHVACENA_FAZA_4));
end


rule "Odluka o trombolizi insertovana"
salience 10
no-loop true
	when
		$odlukaEvent: OdlukaOTromboliziEvent(((statusOdluke != StatusOdluke.PRIHVACENA_FAZA_1) && (statusOdluke != StatusOdluke.PRIHVACENA_FAZA_6)) || (statusOdluke == StatusOdluke.PRIHVACENA_FAZA_4))
	then
		System.out.println("Promena odluke o primeni trombolize na: " + $odlukaEvent.getStatusOdluke());
		retract($odlukaEvent);
end


rule "Faza 5 - Ukoliko postoji hiperdenzni arterijski znak ili edamatozni girus sa zaravnjenim sulkusima, primena terapije nije moguća"
no-loop true
salience 100
	when
		$odlukaEvent: OdlukaOTromboliziEvent(statusOdluke == StatusOdluke.PRIHVACENA_FAZA_5, $znaciIshemije: znaciIshemije)
		$znakIshemije: ZnakIshemije() from $znaciIshemije
		eval($znakIshemije.ordinal() == 1 || $znakIshemije.ordinal() == 2)
	then
		System.out.println("Na CT-u je primecen " + $znakIshemije + ", tako da se pacijentu ne moze primeniti terapija");
		modify ($odlukaEvent) { setStatusOdluke(StatusOdluke.ODBIJENA) };
end
