package forward;

import com.ftn.sbnz.model.models.NIHHS;
import com.ftn.sbnz.model.events.OdlukaOTromboliziEvent;
import com.ftn.sbnz.model.models.StatusOdluke;
import com.ftn.sbnz.model.models.ZnakIshemije;


rule "Faza 4 - Pacijent nije podoban za primenu terapije na osnovu NIHHS skora"
	when
		$nihhs: NIHHS(skor < 4 || skor > 20)
	then
		System.out.println("Pacijent ciji je NIHHS skor " + $nihhs.getSkor() + " nije podoban za primenu terapije.");
		insert(new OdlukaOTromboliziEvent($nihhs.getIdOdluke(), StatusOdluke.ODBIJENA));
end

rule "Faza 4 - Pacijent jeste podoban za primenu terapije na osnovu NIHHS skora"
	when
		$nihhs: NIHHS(skor >= 4 && skor <= 20)
	then
		System.out.println("u pravilu nihhs " + $nihhs.getIdOdluke());
		System.out.println("Pacijent ciji je NIHHS skor " + $nihhs.getSkor() + " je podoban za primenu terapije.");
		insert(new OdlukaOTromboliziEvent($nihhs.getIdOdluke(), StatusOdluke.PRIHVACENA_FAZA_4));
end


rule "Odluka o trombolizi insertovana"
	when
		$odlukaEvent: OdlukaOTromboliziEvent((statusOdluke != StatusOdluke.ODBIJENA) || (statusOdluke == StatusOdluke.PRIHVACENA_FAZA_4) || (statusOdluke != StatusOdluke.PRIHVACENA_FAZA_3))
	then
		System.out.println("Promena odluke o primeni trombolize na: " + $odlukaEvent.getStatusOdluke());
		retract($odlukaEvent)
end


rule "Faza 5 - Ukoliko postoji hiperdenzni arterijski znak ili edamatozni girus sa zaravnjenim sulkusima, primena terapije nije moguća"
no-loop true
salience 100
	when
		$odlukaEvent: OdlukaOTromboliziEvent(statusOdluke == StatusOdluke.PRIHVACENA_FAZA_4, $znaciIshemije: znaciIshemije)
		$znakIshemije: ZnakIshemije() from $znaciIshemije
		eval($znakIshemije.ordinal() == 1 || $znakIshemije.ordinal() == 2)
	then
		System.out.println("Ne primenjuj terapiju: " + $znakIshemije);
		System.out.println("Ne primenjuj terapiju: " + $znaciIshemije);

		modify ($odlukaEvent) { setStatusOdluke(StatusOdluke.ODBIJENA) };
end

rule "Faza 5 - Ukoliko postoji gubitak granice između sive i bele mase ili hipoatenuacija bazalnih ganglija, primena terapije je moguća"
no-loop true
salience 10
	when
		$odlukaEvent: OdlukaOTromboliziEvent(statusOdluke == StatusOdluke.PRIHVACENA_FAZA_4, $znaciIshemije: znaciIshemije)
		$znakIshemije: ZnakIshemije() from $znaciIshemije
		eval($znakIshemije.ordinal() == 0 || $znakIshemije.ordinal() == 3)
	then
		System.out.println("Primeni terapiju: " + $znakIshemije);
		modify ($odlukaEvent) { setStatusOdluke(StatusOdluke.PRIHVACENA_FAZA_5) };
end