package forward;

import com.ftn.sbnz.model.models.NIHHS;
import com.ftn.sbnz.model.events.OdlukaOTromboliziEvent;
import com.ftn.sbnz.model.models.StatusOdluke;


rule "Faza 4 - Pacijent nije podoban za primenu terapije na osnovu NIHHS skora"
	when
		$nihhs: NIHHS(skor < 4 || skor > 20)
	then
		System.out.println("Pacijent ciji je NIHHS skor " + $nihhs.getSkor() + " nije podoban za primenu terapije.");
		insert(new OdlukaOTromboliziEvent($nihhs.getJmbgPacijenta(), StatusOdluke.ODBIJENA));
end

rule "Faza 4 - Pacijent jeste podoban za primenu terapije na osnovu NIHHS skora"
	when
		$nihhs: NIHHS(skor >= 4 && skor <= 20)
	then
		System.out.println("Pacijent ciji je NIHHS skor " + $nihhs.getSkor() + " je podoban za primenu terapije.");
		insert(new OdlukaOTromboliziEvent($nihhs.getJmbgPacijenta(), StatusOdluke.PRIHVACENA_FAZA_4));
end


rule "Odluka o trombolizi insertovana"
	when
		$odlukaEvent: OdlukaOTromboliziEvent()
	then
		System.out.println("Promena odluke o primeni trombolize na: " + $odlukaEvent.getStatusOdluke());
		retract($odlukaEvent)
end